version: 2

project_name: radxa-linkr-debuggerctl

release:
  disable: true

builds:
  - id: radxa-linkr-debuggerctl
    main: ./cmd/radxa-linkr-debuggerctl
    binary: radxa-linkr-debuggerctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X radxa-linkr-debugger/internal/hostcli.Version={{ .Version }}
    flags:
      - -trimpath

archives:
  - id: radxa-linkr-debuggerctl
    ids:
      - radxa-linkr-debuggerctl
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - README.zh-CN.md
      - doc/openocd/*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"
