# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Copyright (c) Radxa Computer (Shenzhen) Co., Ltd.
# Copyright (c) Jiali Chen <chenjiali@radxa.com>

[package]
name = "radxa-linkr-debuggerctl-ng"
version = "0.3.0"
edition = "2021"
license = "LGPL-3.0-or-later"

[[bin]]
name = "radxa-linkr-debuggerctl"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
crossterm = "0.29.0"
humantime = "2.3.0"
ratatui = "0.30.0"
reqwest = { version = "0.13.4", default-features = false, features = ["blocking", "json", "rustls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
sha2 = "0.10.9"
thiserror = "2.0.18"
tungstenite = { version = "0.29.0", features = ["rustls-tls-webpki-roots"] }
serialport = "4.7"
uuid = { version = "1", features = ["v4"] }
ctrlc = "3"
regex = "1"
