# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Copyright (c) Radxa Computer (Shenzhen) Co., Ltd.
# Copyright (c) xzl <xiangzelong@radxa.com>
# Copyright (c) Jiali Chen <chenjiali@radxa.com>

CONFIG_GPIO=y
CONFIG_ADC=y
CONFIG_SENSOR=y
CONFIG_CURRENT_AMP=y
CONFIG_REGULATOR=y
CONFIG_REGULATOR_FIXED=y
CONFIG_I2C=y
CONFIG_SPI=y

CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_CDC_NCM_CLASS=y
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_HWINFO=y
CONFIG_WATCHDOG=y

CONFIG_NETWORKING=y
CONFIG_NET_LOG=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_DHCPV4_SERVER=y
CONFIG_NET_TCP_TIME_WAIT_DELAY=0
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_AUTO_INIT=n
CONFIG_NET_CONFIG_MY_IPV4_ADDR="172.29.203.1"
CONFIG_NET_CONFIG_PEER_IPV4_ADDR="172.29.203.2"
CONFIG_NET_CONFIG_MY_IPV4_GW="172.29.203.2"
CONFIG_NET_DHCPV4_SERVER_ADDR_COUNT=1
CONFIG_NET_DHCPV4_SERVER_OPTION_ROUTER=y
CONFIG_NET_DHCPV4_SERVER_OPTION_DNS_ADDRESS="172.29.203.1"
CONFIG_NET_PKT_RX_COUNT=16
CONFIG_NET_PKT_TX_COUNT=16
CONFIG_NET_BUF_RX_COUNT=64
CONFIG_NET_BUF_TX_COUNT=64
CONFIG_NET_BUF_DATA_SIZE=256
CONFIG_NET_MAX_CONTEXTS=16
CONFIG_NET_MAX_CONN=16
CONFIG_NET_TC_TX_COUNT=1

CONFIG_HTTP_SERVER=y
CONFIG_HTTP_SERVER_VERSION_1=y
CONFIG_HTTP_SERVER_VERSION_2=n
CONFIG_HTTP_SERVER_MAX_CLIENTS=6
CONFIG_HTTP_SERVER_CLIENT_BUFFER_SIZE=512
CONFIG_HTTP_SERVER_MAX_URL_LENGTH=128
CONFIG_HTTP_SERVER_MAX_HEADER_LEN=128
CONFIG_HTTP_SERVER_WEBSOCKET=y
CONFIG_WEBSOCKET_MAX_CONTEXTS=4
CONFIG_RPI_PICO_TEMP=y
CONFIG_CPU_LOAD=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y
CONFIG_THREAD_RUNTIME_STATS=y

CONFIG_JSON_LIBRARY=y
CONFIG_TEST_RANDOM_GENERATOR=y

CONFIG_SERIAL=y
CONFIG_ZVFS_OPEN_MAX=32
CONFIG_ZVFS_EVENTFD_MAX=8
CONFIG_ZVFS_POLL_MAX=16
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_PROMPT_UART="linkr-debugger:~$ "

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=2
CONFIG_BOOT_BANNER=n
CONFIG_MAIN_STACK_SIZE=3072
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_INIT_STACKS=y
CONFIG_THREAD_NAME=y
CONFIG_STACK_SENTINEL=y
CONFIG_HEAP_MEM_POOL_SIZE=8192
